// #[derive(Debug)]
// pub enum Currency {
//     USD,
//     EUR,
//     AFN,
//     ALL,
//     DZD,
//     AOA,
//     ARS,
//     AMD,
//     AWG,
//     AZN,
//     BSD,
//     BHD,
//     BDT,
//     BBD,
//     BYN,
//     BYR,
//     BZD,
//     BMD,
//     BTN,
//     BOB,
//     BOV,
//     BAM,
//     BWP,
//     BRL,
//     BND,
//     BGN,
//     BIF,
//     KHR,
//     CAD,
//     CVE,
//     KYD,
//     CLF,
//     CLP,
//     CNY,
//     COP,
//     COU,
//     KMF,
//     CDF,
//     CRC,
//     HRK,
//     CUC,
//     CUP,
//     CZK,
//     DJF,
//     DOP,
//     EGP,
//     SVC,
//     ERN,
//     ETB,
//     FKP,
//     FJD,
//     XAF,
//     GMD,
//     GEL,
//     GHS,
//     GIP,
//     DKK,
//     GTQ,
//     GNF,
//     GYD,
//     HTG,
//     HNL,
//     HKD,
//     HUF,
//     ISK,
//     INR,
//     IDR,
//     IRR,
//     IQD,
//     ILS,
//     JMD,
//     JPY,
//     JOD,
//     KZT,
//     KES,
//     KPW,
//     KRW,
//     KWD,
//     KGS,
//     LAK,
//     LVL,
//     LBP,
//     LSL,
//     LRD,
//     LYD,
//     LTL,
//     MOP,
//     MKD,
//     MGA,
//     MWK,
//     MYR,
//     MVR,
//     MRO,
//     MUR,
//     MXN,
//     MXV,
//     MDL,
//     MNT,
//     MZN,
//     MMK,
//     NAD,
//     NPR,
//     NIO,
//     NGN,
//     OMR,
//     PKR,
//     PAB,
//     PGK,
//     PYG,
//     PEN,
//     PHP,
//     PLN,
//     QAR,
//     RON,
//     RUB,
//     RWF,
//     SHP,
//     XCD,
//     WST,
//     STD,
//     SAR,
//     RSD,
//     SCR,
//     SLL,
//     SGD,
//     ANG,
//     SBD,
//     SOS,
//     ZAR,
//     SSP,
//     LKR,
//     SDG,
//     SRD,
//     NOK,
//     SZL,
//     SEK,
//     CHE,
//     CHF,
//     CHW,
//     SYP,
//     TWD,
//     TJS,
//     TZS,
//     THB,
//     XOF,
//     NZD,
//     TOP,
//     TTD,
//     TND,
//     TRY,
//     TMT,
//     AUD,
//     UGX,
//     UAH,
//     AED,
//     GBP,
//     USN,
//     USS,
//     UYI,
//     UYU,
//     UZS,
//     VUV,
//     VEF,
//     VND,
//     XPF,
//     MAD,
//     YER,
//     ZMK,
//     ZMW,
//     ZWL,
// }

#[derive(Debug)]
pub enum Currency {
    USD,
    EUR,
}

// Implement a method to convert the enum into a string
impl Currency {
    pub fn to_string(&self) -> String {
        match *self {
            Currency::USD => String::from("USD"),
            Currency::EUR => String::from("EUR"),
        }
    }
}

// pub fn currency_to_string(currency: &Currency) -> &'static str {
//     match currency {
//         Currency::ZWL => "ZWL",
//         Currency::USD => "USD",
//         Currency::EUR => "EUR",
//         Currency::AFN => "AFN",
//         Currency::ALL => "ALL",
//         Currency::DZD => "DZD",
//         Currency::AOA => "AOA",
//         Currency::ARS => "ARS",
//         Currency::AMD => "AMD",
//         Currency::AWG => "AWG",
//         Currency::AZN => "AZN",
//         // Add more cases for the remaining enum variants here
//     }
// }